# Generated by Django 5.2.8 on 2025-11-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_carmodel_dealer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='dealer_id',
        ),
    ]
