# Generated by Django 5.2.8 on 2025-11-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_remove_carmodel_dealer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='dealer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
